Part 1 Clean the Data

In [2]:
import sys, subprocess
def pipq(*pkgs):
    subprocess.run([sys.executable, "-m", "pip", "-q", "install", *pkgs])

pipq("scikit-learn", "pandas", "numpy", "matplotlib", "seaborn")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option("display.max_columns", 60)
np.random.seed(0)
print("pandas", pd.__version__)

pandas 3.0.3

Phase A: Load & Profile
3.2 Getting information

In [4]:
df = pd.read_csv('data.csv', encoding='ISO-8859-1')
display(df.head(3))
print("shape:", df.shape)
display(df.describe())
df.info()
df.isnull().sum()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom

shape: (541909, 8)

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

<class 'pandas.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  str
 1   StockCode    541909 non-null  str
 2   Description  540455 non-null  str
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  str
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  str
dtypes: float64(2), int64(1), str(5)
memory usage: 33.1 MB

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

3.9 Unique values

In [9]:
print("distinct country:", df["Country"].nunique())
print(df["Country"].value_counts())

print("distinct stockcode:", df["StockCode"].nunique())
print(df["StockCode"].value_counts())

print("distinct description:", df["Description"].nunique())
print(df["Description"].value_counts())

print(df["StockCode"].value_counts(dropna=False)) # StockCode and Description are the Product code/name
print(df["Description"].value_counts(dropna=False))

distinct country: 38
Country
United Kingdom          495478
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
USA                        291
Hong Kong                  288
Singapore                  229
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
Name: count, dtype: int64
distinct stockcode: 4070
StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
23609        1
85179a       1
23617        1
90214U       1
47591b       1
Name: count, Length: 4070, dtype: int64
distinct description: 4223
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
                                      ...
LETTER "U" BLING KEY RING                1
wet                                      1
wet boxes                                1
????damages????                          1
lost                                     1
Name: count, Length: 4223, dtype: int64
StockCode
85123A    2313
22423     2203
85099B    2159
47566     1727
20725     1639
          ...
23609        1
85179a       1
23617        1
90214U       1
47591b       1
Name: count, Length: 4070, dtype: int64
Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
                                      ...
LETTER "U" BLING KEY RING                1
wet                                      1
wet boxes                                1
????damages????                          1
lost                                     1
Name: count, Length: 4224, dtype: int64

3.8 Min/max/sum/mean/count

In [26]:
display(df.describe())

print("Num of negative Quantity: ", df[df["Quantity"] < 0].shape[0])
print("Num of negative or zero UnitPrice: ", df[df["UnitPrice"] <= 0].shape[0])

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

Num of negative Quantity:  10624
Num of negative or zero UnitPrice:  2517

3.1 Creating a DataFrame

In [24]:
region_lookup_table = {
    "United Kingdom": "UK&IE",
    "Germany": "Western Europe",
    "France": "Western Europe",
    "EIRE": "UK&IE",
    "Spain": "Southern Europe",
    "Netherlands": "Western Europe",
    "Belgium": "Western Europe",
    "Switzerland": "Western Europe",
    "Portugal": "Southern Europe",
    "Australia": "Oceania",
    "Norway": "Northern Europe",
    "Italy": "Southern Europe",
    "Channel Islands": "UK&IE",
    "Finland": "Northern Europe",
    "Cyprus": "Southern Europe",
    "Sweden": "Northern Europe",
    "Unspecified": "Unknown",
    "Austria": "Western Europe",
    "Denmark": "Northern Europe",
    "Japan": "East Asia",
    "Poland": "Eastern Europe",
    "Israel": "Middle East",
    "USA": "North America",
    "Hong Kong": "East Asia",
    "Singapore": "Southeast Asia",
    "Iceland": "Northern Europe",
    "Canada": "North America",
    "Greece": "Southern Europe",
    "Malta": "Southern Europe",
    "United Arab Emirates": "Middle East",
    "European Community": "Europe",
    "RSA": "Africa",
    "Lebanon": "Middle East",
    "Lithuania": "Eastern Europe",
    "Brazil": "South America",
    "Czech Republic": "Eastern Europe",
    "Bahrain": "Middle East",
    "Saudi Arabia": "Middle East"
}

PHASE B: Select & filter
3.3 Slicing

In [46]:
display(df.iloc[0:3])
df["LineItem"] = df.index
display(df.loc[:, ["Quantity", "UnitPrice"]].head())
df2 = df.set_index("LineItem")
display(df2.loc[0:3])

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,LineRevenue,LineItem
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30,0
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34,1
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00,2

   Quantity  UnitPrice
0         6       2.55
1         6       3.39
2         8       2.75
3         6       3.39
4         6       3.39

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,LineRevenue
LineItem,,,,,,,,,
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom,20.34

3.4 Conditional selection

In [ ]:
print("Cancellations:", df[df["InvoiceNo"].str.startswith("C")].shape[0])
print("Num of negative or zero Quantity: ", df[df["Quantity"] <= 0].shape[0])
print("Num of negative or zero UnitPrice: ", df[df["UnitPrice"] <= 0].shape[0]) # I think I did it previuosly, but I'll just follow instruction

Cancellations: 9288
Num of negative or zero Quantity:  10624
Num of negative or zero UnitPrice:  2517

3.5 Sorting values

In [37]:
df["LineRevenue"] = df["Quantity"] * df["UnitPrice"]
sorted_in_largest_bulk_orders = df.sort_values("Quantity", ascending=False)
print("Largest Bulk Orders: \n", sorted_in_largest_bulk_orders.head(1))
sorted_in_largest_returns = df.sort_values("LineRevenue", ascending=False)
print("Largest returns: \n", sorted_in_largest_returns.head(1))

Largest Bulk Orders:
        InvoiceNo StockCode                  Description  Quantity  \
540421    581483     23843  PAPER CRAFT , LITTLE BIRDIE     80995

           InvoiceDate  UnitPrice  CustomerID         Country  LineRevenue
540421  12/9/2011 9:15       2.08     16446.0  United Kingdom     168469.6
Largest returns:
        InvoiceNo StockCode                  Description  Quantity  \
540421    581483     23843  PAPER CRAFT , LITTLE BIRDIE     80995

           InvoiceDate  UnitPrice  CustomerID         Country  LineRevenue
540421  12/9/2011 9:15       2.08     16446.0  United Kingdom     168469.6

PHASE E: Combine
3.20 Concatenating

In [ ]:
first_half = df[df["InvoiceDate"].dt.month <= 6]
second_half = df[df["InvoiceDate"].dt.month > 6]
pd.concat([first_half, second_half])

3.21 Merging

In [ ]:
region_lookup_df = pd.Series(region_lookup_table)
region_lookup_df.colums = ["Country", "Region"]

df_left = df.merge(region_lookup_df, how="left", on="Country")
df_inner = pd.merge(region_lookup_df, on="Country", how="inner")